version: 2
jobs:
  build:
    working_directory: ~/

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar